### ISSUE TITLE
Is is possible to build gotron on MacOS?

### ISSUE THREAD

**Issue by nikkau** [fbsobreira/gotron-sdk#11]
Hi,

I've just cloned the code, and run `make`. it said:
```
➜  gotron-sdk git:(master) ✗ make
GO111MODULE=on go build -o ./bin/tronctl -ldflags="-X main.version=v234 -X main.commit=4c6c1768 -X main.builtAt=2021-01-29T15:08:52+0900 -X main.builtBy=nikau@cryptochain.network" cmd/main.go
# github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents.go:49:11: undefined: stream
vendor/github.com/rjeczalik/notify/watcher_fsevents.go:200:13: undefined: newStream
make: *** [all] Error 2
```

The OS version is macOS Big Sur, version 11.0.1 (20B29)

Could any one help me?

**Comment by fbsobreira** [comment]
Yes, you can build on intel... tho, seems the error is related with arm64 based Mac... 
https://github.com/rjeczalik/notify/issues/181

the `rjeczalik` is only used in keystore package to find all keystores saved in command line tool, you should be able to remove that feature and build with no problem on arm64
