### ISSUE TITLE
GRPC method GetBlockByNum2 receiving 0 transactions from block 

### ISSUE THREAD

**Issue by MarcSky** [fbsobreira/gotron-sdk#17]
Hello. I have strange problem. I try to save Tron blockchain to my database for future work, but when I using GRPC method GetBlockByNum2 his receiving me 0 transactions, but when I using GetNowBlock2 - that's work great.
What it's can be? Maybe I need use some timeout between calling method GetBlockByNum2 or something wrong with Tron node configuration?

**Comment by fbsobreira** [comment]
you may have a light node, or the block you are checking have no transactions... closing this as stale, please reopen if still have issues with `GetBlockByNum2`
