### ISSUE TITLE
v2.2.2 make error 

### ISSUE THREAD

**Issue by wade-liwei** [fbsobreira/gotron-sdk#29]
go build runtime/cgo: invalid flag in go:cgo_ldflag: -Wl,-rpath -Wl,\\RIGIN/lib (see https://golang.org/s/invalidflag)

**Comment by refiny** [comment]
可以将 Makefile改一下试试，里面有这个配置，\$ORIGIN 改为 $ORIGIN
export CGO_LDFLAGS=-L$(DIR)/bin/lib -Wl,-rpath -Wl,$ORIGIN/lib
export CGO_LDFLAGS_ALLOW=-L$(DIR)/bin/lib -Wl,-rpath -Wl,$ORIGIN/lib
