### ISSUE TITLE
About the  param of Trigercontract function

### ISSUE THREAD

**Issue by chuyijia** [fbsobreira/gotron-sdk#33]
Hello,there!I've been tortured by the trigercontract function these days cause I got stucked when generating the type of "address[]" and "uint256[]" params to json string.Hope u guys can save child from the hell  o((⊙﹏⊙))o.

`
	c, err := grpcs.NewClient(node)
	if err != nil {
		panic(err)
	}
	param0:=map[string]interface{}{"address":"TF17BgPaZYbz8oxbjhriubPDsA7ArKoLX3"}
	param1:=map[string]interface{}{"uint256[]":[]interface{}{"1000000000000000000","3000000000000000000"}}
	param2:=map[string]interface{}{"address[]":[]interface{}{"TXmJUu9LRxfuMdWfq1yvfgrcjktWMmBagT","TRc1toWf5B6sELSM3pycFZkewiYPafmbao"}}
	data:=[]map[string]interface{}{param0,param2,param1}
	data1,_:=json.Marshal(data)
	stringData:=string(data1)
	fmt.Println(stringData)
	
  tx,err:=c.GRPC.TriggerContract("TYAssDXyb8yf5DrxBH9kgkfmU4jZ81SisQ","TP2N1dERMjH1TpfvG2iEJphGFj7xUFB3HD","sendToken(address,address[],uint256[])",stringData,300000000, 0, "", 0)
	signTx, err := 
        sign.SignTransaction(tx.Transaction,"oe9e798a06c89f3abc74dc416feef18cc8b00303ace9b7539a8115b65a1abdcf")
	if err != nil {
		panic(err)
	}
	err = c.BroadcastTransaction(signTx)
	if err != nil {
		panic(err)
        }
	txid:=strings.TrimLeft(common.BytesToHexString(tx.GetTxid()),"0x")
	t.JSON(http.StatusOK, gin.H{"Code":1,"result":txid})
`

The error show that "can not take []interface as []string".Should I change the key "address[]"  to "address"?which seems to beconflicted with the requirement of tron contract interaction,what should i do to rectify the code?

Your reply will be highly appreciated!tks alot!  ヾ(•ω•`)o

**Comment by todd-woko** [comment]
You can see how it works in the `abi` package, build parameters data, sign and broadcast

**Comment by chuyijia** [comment]
> You can see how it works in the `abi` package, build parameters data, sign and broadcast

大哥，可以看看我哪里出了问题不，字典键名传入”address[]“和"uint256[]"就报错，但是和其他函数交互时，例如transfer(address,uint256)这种函数时，传入”address“和"uint256"就正常，是传的参数有问题吗

**Comment by todd-woko** [comment]
我针对我的合约重写了他的构建交易，签名和广播，使用他外部的这些方法我和你有一样的问题，我建议你去看他的源码然后自己实现

**Comment by todd-woko** [comment]
> > You can see how it works in the `abi` package, build parameters data, sign and broadcast
> 
> 大哥，可以看看我哪里出了问题不，字典键名传入”address[]“和"uint256[]"就报错，但是和其他函数交互时，例如transfer(address,uint256)这种函数时，传入”address“和"uint256"就正常，是传的参数有问题吗

我是针对我的合约重写了构建交易的方法，他提供的方法有很多的限制，可能是因为 tron 的底层不支持，我之前也提过issue，只不过好像这个项目没有更新了，我建议你也重写
