### ISSUE TITLE
should I run tron-cli? 

### ISSUE THREAD

**Issue by armagg** [fbsobreira/gotron-sdk#4]
do I need to run tron-cli in my computer to use this cli?

**Comment by fbsobreira** [comment]
No need tron-cli... the binary name is `tronctl`

```
$ git pull -r origin master
$ make
$ ./bin/tronctl keys import-private-key YOUR_PRIVATE_KEY A_NAME_FOR_YOUR_ACCOUNT
```

**Comment by armagg** [comment]
can you provide me some usage cases and examples? I want to balance and make transactions with some API automatically
