### ISSUE TITLE
How to sign the tx with private key?

### ISSUE THREAD

**Issue by cryptodogge** [fbsobreira/gotron-sdk#42]
As far as I know, I find there are no methods to sign the tx with the private key, only keystore allowed. Could you show me how to use the private key to make a transaction?

**Comment by fbsobreira** [comment]
Hi! you can also create you own function, just follow example: 
`

import (
	"crypto/sha256"

	"github.com/ethereum/go-ethereum/crypto"
	"google.golang.org/protobuf/proto"
)

rawData, err := proto.Marshal(tx.GetRawData())
if err != nil {
	return nil, err
}
h256h := sha256.New()
h256h.Write(rawData)
hash := h256h.Sum(nil)

signature, err := crypto.Sign(hash,privateKey)
if err != nil {
	return nil, err
}
tx.Signature = append(tx.Signature, signature)
`
