### ISSUE TITLE
Estimate transaction TRC20 fee

### ISSUE THREAD

**Issue by ranjbar-dev** [fbsobreira/gotron-sdk#44]
Hello thank`s for great work,
I was wondering do you know how I can estimate transferring TRC20 fee  on Tron network ? 
I could find good solution for transferring TRC10 fee and its here 
https://github.com/ranjbar-dev/tron-wallet/blob/main/fee.go#L9

**Comment by fbsobreira** [comment]
https://developers.tron.network/docs/set-feelimit#how-to-estimate-energy-consumption
