### ISSUE TITLE
how to use functionality of Tron network by this SDK

### ISSUE THREAD

**Issue by gpassing** [fbsobreira/gotron-sdk#48]
i can not find correct usibility like creating account and transfering tokens :/
the code is seems left

**Comment by fbsobreira** [comment]
Create an account: https://github.com/fbsobreira/gotron-sdk/blob/c4daceb828f02b51e5082153c669e71d43899496/pkg/account/creation.go#L31

send tokens: https://github.com/fbsobreira/gotron-sdk/blob/c4daceb828f02b51e5082153c669e71d43899496/cmd/subcommands/account.go#L118

**Comment by gpassing** [comment]
thank you so much
