### ISSUE TITLE
Signed text verification

### ISSUE THREAD

**Issue by kewyn-latorre** [fbsobreira/gotron-sdk#49]
How can I verify a message signed by the Tronlink extension?

Basically I need to verify messages signed by frontend users using Tronlink.
I give them a message "random_message" and the frontend calls back with the signature hash. I then need to verify that hash with the message and the address.

I tried adapting the go-ethereum functions to do it but I just have no idea how the Tronlink signatures differ from Ethereum's.

**Comment by fbsobreira** [comment]
this SDK does not have verify message yet implemented, but to give you some ideas of how to verify, have to get the context, long time ago some dApps started creating message signature using fixed length in protocol message... even if message has more or less then 32byes.. also a wrong length for signature header `\x19`

Usually it should compute the hash of a message and sign that message, but not all dApps do like this, some use raw message, so if sent "RANDOM MESSAGE", it should sign the hash of `\x19TRON Signed Message:\n\14RANDOM MESSAGE`, or use the hash of hashed message `\x19TRON Signed Message:\n32XXX...`, instead it uses `32` for any message... it may be the case you not getting the correct verification...

you can use this as reference in python with ETH lib... `https://github.com/LedgerHQ/app-tron/blob/c6cf4cbae1b4902ec8834e37ce5ad0dae58577a9/examples/validateSignature.py#L31` 

or golang like this:
```
message := []byte("YOUR MESSAGE") // can be the hash here
toSign := []byte("\x19TRON Signed Message:\n")
toSign = append(toSign, []byte("32")...) // suppose to be length of message like -> []byte(fmt.Sprintf("%d", len(message)))...)
toSign = append(toSign, message...)

// and then keccak256 to generate the singable hash
d := sha3.NewLegacyKeccak256()
d.Write(message...)
hash := d.Sum(nil)
```

and to validate message try with 

```
sigPublicKey, _ := secp256k1.RecoverPubkey(hash, signature)
// then convert the pub key to address
```

**Comment by fbsobreira** [comment]
JS implementation: https://github.com/tronprotocol/tronweb/blob/859253856c79d3aff26ec6c89afefc73840d648d/src/lib/trx.js#L606

**Comment by fbsobreira** [comment]
please check cmd for example with gorton-sdk https://github.com/fbsobreira/gotron-sdk/blob/874fc4b6eccc22594815cba329d4e4f08e9800af/cmd/subcommands/account.go#L656

notice that Tronscan uses hash of message to append into Message hash.... maybe the case you not been able to verify...

**Comment by Kewyn-Vieira** [comment]
I got it working. Thank you very much!
Here's the full code if anyone needs it in the future:

```
import (
	"encoding/hex"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/fbsobreira/gotron-sdk/pkg/address"
	"golang.org/x/crypto/sha3"
)

func TronlinkVerifySignature(from, sigHex, msg string) bool {
	// Remove prefix
	if sigHex[:2] == "0x" {
		sigHex = sigHex[2:]
	}

	if len(sigHex) != 130 {
		return false
	}

	message := []byte(msg)
	toSign := []byte("\x19TRON Signed Message:\n")
	toSign = append(toSign, []byte("32")...)
	toSign = append(toSign, message...)

	d := sha3.NewLegacyKeccak256()
	d.Write(toSign)
	hash := d.Sum(nil)

	sigBytes, err := hex.DecodeString(sigHex)
	if err != nil {
		return false
	}

	if sigBytes[crypto.RecoveryIDOffset] == 27 || sigBytes[crypto.RecoveryIDOffset] == 28 {
		sigBytes[crypto.RecoveryIDOffset] -= 27 // Transform yellow paper V from 27/28 to 0/1
	}

	pubKey, err := crypto.SigToPub(hash, sigBytes)
	if err != nil {
		return false
	}

	walletAddress := address.PubkeyToAddress(*pubKey)

	return walletAddress.String() == from
}
```
