### ISSUE TITLE
Help message with error

### ISSUE THREAD

**Issue by h4r7w3l1** [fbsobreira/gotron-sdk#5]
In usages help message.  May confused for a second  😄

_tronc**l**t_  occurs once, though correct _tronc**t**l_  12 times
```
user@localhost:~> tronclt
bash: tronclt: command not found
```

[https://github.com/fbsobreira/gotron-sdk/blob/41cbd6cbc08969b726e9e434cb3c726bb2bffa3e/cmd/subcommands/root.go#L85](url)

**Comment by fbsobreira** [comment]
binary may not be installed in you path... if you can find in you root folder, try with `./tronctl` or copy the tronctl binary to you path env folder...
