### ISSUE TITLE
Why does the /protocol.Wallet/GetBlockByNum2 interface not exist in offical doc?

### ISSUE THREAD

**Issue by hero5512** [fbsobreira/gotron-sdk#60]
I didn't see anything about GetBlockByNum2 in https://cn.developers.tron.network/reference/getblockbynum. So which node are you using? thank you

**Comment by fbsobreira** [comment]
api.proto from official repo:
https://github.com/tronprotocol/protocol/blob/393732abcb359cea591d06a6179ee4bfca8662bd/api/api.proto#L416
