### ISSUE TITLE
How to invoke functions defined in a smart contract?

### ISSUE THREAD

**Issue by UpwardGrowth** [fbsobreira/gotron-sdk#73]
I want to invoke functions in my smart contract but I cannot find a way to do it. I am able to easily call the functions using tronweb, but I am unsure how to call them using Go or the gotron-sdk.

**Comment by fbsobreira** [comment]
this this: https://github.com/fbsobreira/gotron-sdk/blob/64b45a6a22e0e0a612c5e47b55184130e289b0c3/pkg/client/contracts_test.go#L78
