### ISSUE TITLE
undefined: secp256k1.RecoverPubkey

### ISSUE THREAD

**Issue by luoxiandong** [fbsobreira/gotron-sdk#77]
Compile the Linux environment running file on Apple Mac computer error:
pkg/keystore/account.go:184:33: undefined: secp256k1.RecoverPubkey
`git clone https://github.com/fbsobreira/gotron-sdk.git
`
`GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -o g-linux cmd/main.go`
version:v2.3.0
![telegram-cloud-photo-size-5-6161183517745198571-y](https://user-images.githubusercontent.com/19297244/230725066-c1025fd2-cabe-4592-9630-f1f29b4577ed.jpg)
How to solve it？

**Comment by fbsobreira** [comment]
this is a cross compile issue as referred in go-ethereum: https://github.com/ethereum/go-ethereum/issues/15662 you can use xgo to cross compile this repo as well... check: https://github.com/crazy-max/xgo
