### ISSUE TITLE
Upgrade to the latest version, unable to start,error: undefined: secp256k1.RecoverPubkey

### ISSUE THREAD

**Issue by 15365917109** [fbsobreira/gotron-sdk#80]
github.com\fbsobreira\gotron-sdk@v0.0.0-20230418195951-b7bfbf1c0ade\pkg\keystore\account.go:184:33: undefined: secp256k1.RecoverPubkey

**Comment by fbsobreira** [comment]
Please check #77

**Comment by 15365917109** [comment]
The go version has been reduced from 1.20 to 1.19.2. But it doesn't work for my computer. Please reinstall Windows and then install 1.19.2

**Comment by LFXiaoFei** [comment]
> github.com\fbsobreira\[gotron-sdk@v0.0.0-20230418195951-b7bfbf1c0ade](mailto:gotron-sdk@v0.0.0-20230418195951-b7bfbf1c0ade)\pkg\keystore\account.go:184:33: undefined: secp256k1.RecoverPubkey

Are you ok?I also encountered the same problem.Please help me.

**Comment by ygcool** [comment]
same question

**Comment by 15365917109** [comment]
> > github.com\fbsobreira[ [gotron-sdk@v0.0.0-20230418195951-b7bfbf1c0ade](mailto:gotron-sdk@v0.0.0-20230418195951-b7bfbf1c0ade) ]( [mailto:gotron-sdk@v0.0.0-20230418195951-b7bfbf1c0ade](mailto:gotron-sdk@v0.0.0-20230418195951-b7bfbf1c0ade) )\pkg\keystore\account.go:184:33: 未定义: secp 256k1。恢复公钥
> 
> 你还好吗？我也遇到了同样的问题。请帮助我。

通过xgo进行打包

**Comment by csquan** [comment]
遇到了同样问题 xgo怎么解决这个问题？具体步骤是啥？

**Comment by fbsobreira** [comment]
have removed RecoverPubkey for windows build due Go-Ethereum CGO issues...
