### ISSUE TITLE
Burn TRX to gain energy

### ISSUE THREAD

**Issue by aliworkshop** [fbsobreira/gotron-sdk#83]
hi every one
according to Tron energy calculate page we can burn tron to gain more energy than freezing
https://tronstation.io/calculator

but there is no method to burn tron from source account in gotron-sdk!

how should we do that ?

**Comment by fbsobreira** [comment]
You dont burn TRX prior the transaction, to `pay` energy using TRX (`burn`) you just submit a transaction. Node will try to consume the Energy from frozen TRX, if not enough, it will but your TRX automatically to `pay` for the energy. The maximum TRX to be burned can be set in `RawData.FeeLimit` it works similar to ETH `GasLimit`

**Comment by aliworkshop** [comment]
According to the calculator page, you can Burn TRX for gaining Energy as like freezing
we have the freeze method in Tron SDK but don't have the burn method
I wish we could burn TRX using gotron-sdk
