### ISSUE TITLE
undefined: secp256k1.RecoverPubkey ？

### ISSUE THREAD

**Issue by csquan** [fbsobreira/gotron-sdk#96]
undefined: secp256k1.RecoverPubkey?use xgo?How?

**Comment by richardsric7** [comment]
i also got this error. how can this be?

**Comment by fbsobreira** [comment]
please check #77 .
for which cross platform ware you trying to compile?

**Comment by csquan** [comment]
windows

**Comment by fbsobreira** [comment]
have removed RecoverPubkey for windows build due Go-Ethereum CGO issues...
