### ISSUE TITLE
how to use mnemonic to privateKey and then to sign Tx?

### ISSUE THREAD

**Issue by csquan** [fbsobreira/gotron-sdk#97]
when I create account ,I only got mnemonic .and how to convert to privateKey and sign TX?

**Comment by fbsobreira** [comment]
you can use `FromMnemonicSeedAndPassphrase`
usually in other wallets passphrase is empty string `""` index `0` for first account... 
if you need to change the whole path, you can also implement the HD derivation.

https://github.com/fbsobreira/gotron-sdk/blob/a6734d0f98885f901b9179a635ea0eaec00ab421/pkg/keys/mnemonic.go#L12
