### ISSUE TITLE
mnemonic and address not sync?

### ISSUE THREAD

**Issue by csquan** [fbsobreira/gotron-sdk#98]
I use code  
acc := account.Creation{
		Name:       "name1",
		Passphrase: "",
	}

	if err := account.CreateNewLocalAccount(&acc); err != nil {
		return "", "", err
	}
	addr, _ := store.AddressFromAccountName(acc.Name)
get acc.Mnemonic and addr,but when I inport mnemonic into tp,it show address different?does it have some wrong?

**Comment by fbsobreira** [comment]
please check the mnemonic path, we use `"44'/195'/0'/0/0"` as default for first account on mnemonic... must check if tp use the same path to derive address...
